/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JogoOrderNumbers;

import com.mysql.jdbc.PreparedStatement;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author henrique
 */
public class Jogo extends javax.swing.JFrame {
    String nome=null;
    Tabuleiro tb=new Tabuleiro();
    TelaVenceu tv;
    TelaMenu ti;
    TelaRegras tr;
     AudioClip Som;
     Timer timer;  
     ConectarMysql conectar;
    private int currentSegundo = 0;
    private int currentMinuto = 0;
    private int currentHora = 0;
    private int velocidade = 1000;
    
    
     
    
     
     public void Som(){
            Som.stop();
            Som.play();
            
            
            
   
     }
         
   
    /**
     * Creates new form Interface
     */
    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bt2 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt13 = new javax.swing.JButton();
        bt14 = new javax.swing.JButton();
        bt15 = new javax.swing.JButton();
        bt16 = new javax.swing.JButton();
        jlJogadas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlTempo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbJogadas = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        btMenu = new javax.swing.JButton();
        btRegras = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(19, 19, 19));
        setFocusable(false);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(38, 50, 50));
        jPanel4.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 178, 8));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 178, 8), 10));
        jPanel1.setToolTipText("");

        bt2.setBackground(new java.awt.Color(15, 193, 23));
        bt2.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt2.setForeground(new java.awt.Color(254, 254, 254));
        bt2.setToolTipText("");
        bt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt2.setFocusable(false);
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt1.setBackground(new java.awt.Color(1, 157, 17));
        bt1.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt1.setForeground(new java.awt.Color(254, 254, 254));
        bt1.setToolTipText("");
        bt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt1.setFocusable(false);
        bt1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bt1MouseMoved(evt);
            }
        });
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt3.setBackground(new java.awt.Color(1, 157, 17));
        bt3.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt3.setForeground(new java.awt.Color(254, 254, 254));
        bt3.setToolTipText("");
        bt3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt3.setFocusable(false);
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setBackground(new java.awt.Color(46, 98, 225));
        bt4.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt4.setForeground(new java.awt.Color(254, 254, 254));
        bt4.setToolTipText("");
        bt4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt4.setFocusable(false);
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setBackground(new java.awt.Color(46, 98, 225));
        bt5.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt5.setForeground(new java.awt.Color(254, 254, 254));
        bt5.setToolTipText("");
        bt5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt5.setFocusable(false);
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setBackground(new java.awt.Color(1, 157, 17));
        bt6.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt6.setForeground(new java.awt.Color(254, 254, 254));
        bt6.setToolTipText("");
        bt6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt6.setFocusable(false);
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt7.setBackground(new java.awt.Color(46, 98, 225));
        bt7.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt7.setForeground(new java.awt.Color(254, 254, 254));
        bt7.setToolTipText("");
        bt7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt7.setFocusable(false);
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt8.setBackground(new java.awt.Color(1, 157, 17));
        bt8.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt8.setForeground(new java.awt.Color(254, 254, 254));
        bt8.setToolTipText("");
        bt8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt8.setFocusable(false);
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt9.setBackground(new java.awt.Color(1, 157, 17));
        bt9.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt9.setForeground(new java.awt.Color(254, 254, 254));
        bt9.setToolTipText("");
        bt9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt9.setFocusable(false);
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt10.setBackground(new java.awt.Color(46, 98, 225));
        bt10.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt10.setForeground(new java.awt.Color(254, 254, 254));
        bt10.setToolTipText("");
        bt10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt10.setFocusable(false);
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });

        bt11.setBackground(new java.awt.Color(1, 157, 17));
        bt11.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt11.setForeground(new java.awt.Color(254, 254, 254));
        bt11.setToolTipText("");
        bt11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt11.setFocusable(false);
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });

        bt12.setBackground(new java.awt.Color(46, 98, 225));
        bt12.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt12.setForeground(new java.awt.Color(254, 254, 254));
        bt12.setToolTipText("");
        bt12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt12.setFocusable(false);
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });

        bt13.setBackground(new java.awt.Color(46, 98, 225));
        bt13.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt13.setForeground(new java.awt.Color(254, 254, 254));
        bt13.setToolTipText("");
        bt13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt13.setFocusable(false);
        bt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt13ActionPerformed(evt);
            }
        });

        bt14.setBackground(new java.awt.Color(1, 157, 17));
        bt14.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt14.setForeground(new java.awt.Color(254, 254, 254));
        bt14.setToolTipText("");
        bt14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt14.setFocusable(false);
        bt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt14ActionPerformed(evt);
            }
        });

        bt15.setBackground(new java.awt.Color(46, 98, 225));
        bt15.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt15.setForeground(new java.awt.Color(254, 254, 254));
        bt15.setToolTipText("");
        bt15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt15.setFocusable(false);
        bt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt15ActionPerformed(evt);
            }
        });

        bt16.setBackground(new java.awt.Color(1, 157, 17));
        bt16.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        bt16.setForeground(new java.awt.Color(254, 254, 254));
        bt16.setToolTipText("");
        bt16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bt16.setFocusable(false);
        bt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bt9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt8))
                    .addComponent(bt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlJogadas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt1, bt10, bt11, bt12, bt13, bt14, bt15, bt16, bt2, bt3, bt5, bt6, bt7, bt8, bt9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jlJogadas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt3)
                            .addComponent(bt4))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt7)
                            .addComponent(bt8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt6)
                            .addComponent(bt5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt10)
                    .addComponent(bt9)
                    .addComponent(bt11)
                    .addComponent(bt12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt14)
                    .addComponent(bt13)
                    .addComponent(bt15)
                    .addComponent(bt16)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bt1, bt10, bt11, bt12, bt13, bt14, bt15, bt16, bt2, bt3, bt4, bt5, bt6, bt7, bt8, bt9});

        jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 252, 253));
        jLabel3.setText("Tempo: ");
        jLabel3.setBorder(null);
        jLabel3.setFocusable(false);

        jlTempo.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jlTempo.setForeground(new java.awt.Color(251, 252, 253));
        jlTempo.setText("00:00:00");
        jlTempo.setBorder(null);
        jlTempo.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 252, 253));
        jLabel2.setText("Jogadas: ");
        jLabel2.setBorder(null);
        jLabel2.setFocusable(false);

        lbJogadas.setBackground(new java.awt.Color(15, 152, 244));
        lbJogadas.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        lbJogadas.setForeground(new java.awt.Color(251, 252, 253));
        lbJogadas.setText("0");
        lbJogadas.setBorder(null);
        lbJogadas.setFocusable(false);

        btSair.setBackground(new java.awt.Color(205, 15, 21));
        btSair.setFont(new java.awt.Font("Abyssinica SIL", 3, 16)); // NOI18N
        btSair.setForeground(new java.awt.Color(254, 254, 254));
        btSair.setText("Sair");
        btSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 2));
        btSair.setFocusable(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btMenu.setBackground(new java.awt.Color(1, 131, 4));
        btMenu.setFont(new java.awt.Font("Abyssinica SIL", 3, 16)); // NOI18N
        btMenu.setForeground(new java.awt.Color(254, 254, 254));
        btMenu.setText("Menu");
        btMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 2));
        btMenu.setFocusable(false);
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });

        btRegras.setBackground(new java.awt.Color(25, 104, 240));
        btRegras.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 3, 16)); // NOI18N
        btRegras.setForeground(new java.awt.Color(254, 254, 254));
        btRegras.setText("?");
        btRegras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 2));
        btRegras.setFocusable(false);
        btRegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRegras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbJogadas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlTempo)
                    .addComponent(jLabel2)
                    .addComponent(lbJogadas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btMenu)
                    .addComponent(btRegras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt16ActionPerformed
      Som();
        tb.MudarPosicao(3, 3);
        exibir();
        CalcularJogadas();
         venceu();
        
    }//GEN-LAST:event_bt16ActionPerformed

    private void bt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt15ActionPerformed
          Som();
        tb.MudarPosicao(3, 2);
        exibir();
        CalcularJogadas();
         venceu();
       
    }//GEN-LAST:event_bt15ActionPerformed

    private void bt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt14ActionPerformed
 Som(); 
        tb.MudarPosicao(3, 1);
        exibir();
        CalcularJogadas();
         venceu();
        
    }//GEN-LAST:event_bt14ActionPerformed

    private void bt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt13ActionPerformed
          Som();
        tb.MudarPosicao(3, 0);
        exibir();
        CalcularJogadas();
         venceu();
       
    }//GEN-LAST:event_bt13ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
 Som();  
        tb.MudarPosicao(2, 3);
        exibir();
        CalcularJogadas();
         venceu();
        
    }//GEN-LAST:event_bt12ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        Som();
        tb.MudarPosicao(2, 2);
        exibir();
        CalcularJogadas();
         venceu();
       
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        Som();
        tb.MudarPosicao(2, 1);
        exibir();
        CalcularJogadas();
         venceu();
       
    }//GEN-LAST:event_bt10ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
          Som();
        tb.MudarPosicao(2, 0);
        exibir();
        CalcularJogadas();
         venceu();
       
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
         Som();
        tb.MudarPosicao(1, 3);
        exibir();
        CalcularJogadas();
         venceu();
        
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        Som();
        tb.MudarPosicao(1, 2);
        exibir();
        CalcularJogadas();
         venceu();
        
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
         Som();
        tb.MudarPosicao(1, 1);
        exibir();
        CalcularJogadas();
         venceu();
       
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
 Som(); 
        tb.MudarPosicao(1, 0);
        exibir();
        CalcularJogadas();
         venceu();
        
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        Som();
        tb.MudarPosicao(0, 3);
        exibir();
        CalcularJogadas();
         venceu();
       
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        Som();
        tb.MudarPosicao(0, 2);
        exibir();
        CalcularJogadas();
         venceu();
        
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        Som();
        tb.MudarPosicao(0, 0);
        exibir();
        CalcularJogadas();
         venceu();
       
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseMoved

    }//GEN-LAST:event_bt1MouseMoved

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
         Som();
        tb.MudarPosicao(0, 1);
        exibir();
        CalcularJogadas();
         venceu();
       
    }//GEN-LAST:event_bt2ActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        ti= new TelaMenu();
        ti.setVisible(true);
        dispose();
    }//GEN-LAST:event_btMenuActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegrasActionPerformed
       
        if(tr==null){
                tr=new TelaRegras();
                tr.getbtVoltar().setEnabled(false);
       tr.setVisible(true);
        } else {
             tr.setVisible(true);
             tr.getbtVoltar().setEnabled(false);
             tr.setExtendedState(NORMAL);
            
        }
       
    }//GEN-LAST:event_btRegrasActionPerformed

    public void venceu(){
       if(tb.Vence()){
           GuardarDados();
           this.Som=java.applet.Applet.newAudioClip(getClass().getResource("laugh_1.wav"));
           this.Som.play();
           TelaVenceu();
          
          
           
       }else;
    }
    
    public void TelaVenceu(){
         tv= new TelaVenceu();
           tv.setTextjlNome(this.nome);
           tv.setTextjlJogadas(this.lbJogadas.getText());
           tv.setTextjlTempo(this.jlTempo.getText());
           tv.setVisible(true);
           dispose();
    }
    public void GuardarDados(){
        timer.stop();
        conectar=new ConectarMysql();
      

        String sql;
       
        String jogadas=this.lbJogadas.getText();
        String tempo=this.jlTempo.getText();
        
        sql="insert into Jogador  values(?,?,?)";
       
        try {
            java.sql.PreparedStatement ps= conectar.conectar().prepareStatement(sql);
           
           
            ps.setString(1, nome);
            ps.setString(2, jogadas);
            ps.setString(3, tempo);
           
            ps.executeUpdate();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        
    }
    public void CalcularJogadas(){
       
        lbJogadas.setText(String.valueOf(tb.contJogadas));
    }
    public void exibir(){
        
       
        bt1.setText(String.valueOf(tb.getTabuleiro()[0][0]));
        bt1.setBackground(Color.BLUE);
        bt1.setBorderPainted(true);
        bt2.setText(String.valueOf(tb.getTabuleiro()[0][1]));
        bt2.setBackground(new java.awt.Color(1,157,17));
        bt2.setBorderPainted(true);
        bt3.setText(String.valueOf(tb.getTabuleiro()[0][2]));
        bt3.setBackground(Color.BLUE);
        bt3.setBorderPainted(true);
        bt4.setText(String.valueOf(tb.getTabuleiro()[0][3]));
        bt4.setBackground(new java.awt.Color(1,157,17));
        bt4.setBorderPainted(true);
        bt5.setText(String.valueOf(tb.getTabuleiro()[1][0]));
        bt5.setBackground(new java.awt.Color(1,157,17));
        bt5.setBorderPainted(true);
        bt6.setText(String.valueOf(tb.getTabuleiro()[1][1]));
        bt6.setBackground(Color.BLUE);
        bt6.setBorderPainted(true);
        bt7.setText(String.valueOf(tb.getTabuleiro()[1][2]));
        bt7.setBackground(new java.awt.Color(1,157,17));
        bt7.setBorderPainted(true);
        bt8.setText(String.valueOf(tb.getTabuleiro()[1][3]));
        bt8.setBackground(Color.BLUE);
        bt8.setBorderPainted(true);
        bt9.setText(String.valueOf(tb.getTabuleiro()[2][0]));
        bt9.setBackground(Color.BLUE);
        bt9.setBorderPainted(true);
        bt10.setText(String.valueOf(tb.getTabuleiro()[2][1]));
        bt10.setBackground(new java.awt.Color(1,157,17));
        bt10.setBorderPainted(true);
        bt11.setText(String.valueOf(tb.getTabuleiro()[2][2]));
        bt11.setBackground(Color.BLUE);
        bt11.setBorderPainted(true);
        bt12.setText(String.valueOf(tb.getTabuleiro()[2][3]));
        bt12.setBackground(new java.awt.Color(1,157,17));
        bt12.setBorderPainted(true);
        bt13.setText(String.valueOf(tb.getTabuleiro()[3][0]));
        bt13.setBackground(new java.awt.Color(1,157,17));
        bt13.setBorderPainted(true);
        bt14.setText(String.valueOf(tb.getTabuleiro()[3][1]));
        bt14.setBackground(Color.BLUE);
        bt14.setBorderPainted(true);
        bt15.setText(String.valueOf(tb.getTabuleiro()[3][2]));
        bt15.setBackground(new java.awt.Color(1,157,17));
        bt15.setBorderPainted(true);
        bt16.setText(String.valueOf(tb.getTabuleiro()[3][3]));
        bt16.setBackground(Color.BLUE);
        bt16.setBorderPainted(true);
       
        
      if(bt1.getText().equals("16")){
        bt1.setBackground(new java.awt.Color(255,178,8));
        bt1.setText("");
        bt1.setBorderPainted(false);
    
     }else;
          if(bt2.getText().equals("16")){
        
       
        bt2.setText("");
 
        bt2.setBackground(new java.awt.Color(255,178,8));
        bt2.setBorderPainted(false);
       
       
     }else  if(bt3.getText().equals("16")){
        
        bt3.setText("");
      
        bt3.setBackground(new java.awt.Color(255,178,8));
        bt3.setBorderPainted(false);
       
     }else  if(bt4.getText().equals("16")){
        
        bt4.setText("");
       
        bt4.setBackground(new java.awt.Color(255,178,8));
        bt4.setBorderPainted(false);
       
     }else  if(bt5.getText().equals("16")){
         
        bt5.setText("");
        
        bt5.setBackground(new java.awt.Color(255,178,8));
        bt5.setBorderPainted(false);
       
     }else  if(bt6.getText().equals("16")){
         bt6.setText("");
       
         bt6.setBackground(new java.awt.Color(255,178,8));
         bt6.setBorderPainted(false);
        
     }else  if(bt7.getText().equals("16")){
         
        bt7.setText("");
      
        bt7.setBackground(new java.awt.Color(255,178,8));
        bt7.setBorderPainted(false);
       
     }else  if(bt8.getText().equals("16")){
        
        bt8.setText("");
      
        bt8.setBackground(new java.awt.Color(255,178,8));
        bt8.setBorderPainted(false);
       
     }else  if(bt9.getText().equals("16")){
        
        bt9.setText("");
       
        bt9.setBackground(new java.awt.Color(255,178,8));
        bt9.setBorderPainted(false);
       
     }else  if(bt10.getText().equals("16")){
        
        bt10.setText("");
      
        bt10.setBackground(new java.awt.Color(255,178,8));
        bt10.setBorderPainted(false);
       
     }else  if(bt11.getText().equals("16")){
         
        bt11.setText("");
      
        bt11.setBackground(new java.awt.Color(255,178,8));
        bt11.setBorderPainted(false);
        
     }else  if(bt12.getText().equals("16")){
        
        bt12.setText("");
      
        bt12.setBackground(new java.awt.Color(255,178,8));
        bt12.setBorderPainted(false);
       
     }else  if(bt13.getText().equals("16")){
        
        bt13.setText("");
       
       bt13.setBackground(new java.awt.Color(255,178,8));
       bt13.setBorderPainted(false);
     }else  if(bt14.getText().equals("16")){
        
        bt14.setText("");
      
        bt14.setBackground(new java.awt.Color(255,178,8));
        bt14.setBorderPainted(false);
       
     }else  if(bt15.getText().equals("16")){
         
        bt15.setText("");
       
        bt15.setBackground(new java.awt.Color(255,178,8));
       bt15.setBorderPainted(false);
     }else  if(bt16.getText().equals("16")){
         
        bt16.setText("");
       
        bt16.setBackground(new java.awt.Color(255,178,8));
        bt16.setBorderPainted(false);
     }else;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }
    

    public void iniciarContagem() {
        ActionListener action = new ActionListener() {  
            public void actionPerformed(ActionEvent e) {  
                currentSegundo++;
                
                if(currentSegundo==60){
                    currentMinuto++;
                    currentSegundo = 0;
                }
                
                if(currentMinuto==60){
                    currentHora++;
                    currentMinuto = 0;
                }
                
                String hr = currentHora <= 9? "0"+currentHora:currentHora+"";
                String min = currentMinuto <= 9? "0"+currentMinuto:currentMinuto+"";
                String seg = currentSegundo <= 9? "0"+currentSegundo:currentSegundo+"";
                
                jlTempo.setText(hr+":"+min+":"+seg);  
            }  
        };  
        this.timer = new Timer(velocidade, action);  
        this.timer.start();
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt13;
    private javax.swing.JButton bt14;
    private javax.swing.JButton bt15;
    private javax.swing.JButton bt16;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btRegras;
    private javax.swing.JButton btSair;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlJogadas;
    private javax.swing.JLabel jlTempo;
    private javax.swing.JLabel lbJogadas;
    // End of variables declaration//GEN-END:variables
}
