/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JogoOrderNumbers;

import java.applet.AudioClip;
import javax.swing.JTextField;

/**
 *
 * @author henrique
 */
public class TelaMenu extends javax.swing.JFrame {
    
    Jogo jg;
    

    /**
     * Creates new form TelaInicial
     */
    public TelaMenu() {
        initComponents();
    
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome = new javax.swing.JTextField();
        btJogar = new javax.swing.JButton();
        btRecordes = new javax.swing.JButton();
        btRegras = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(19, 2, 241));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(38, 50, 50));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 69, 254), 6));
        jPanel1.setFont(new java.awt.Font("Abyssinica SIL", 3, 36)); // NOI18N

        nome.setBackground(new java.awt.Color(38, 50, 50));
        nome.setFont(new java.awt.Font("Abyssinica SIL", 0, 24)); // NOI18N
        nome.setForeground(new java.awt.Color(254, 254, 254));
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 238, 2), 2));
        nome.setCaretColor(new java.awt.Color(254, 254, 254));
        nome.setMaximumSize(new java.awt.Dimension(5, 1));
        nome.setPreferredSize(new java.awt.Dimension(4, 1));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        btJogar.setBackground(new java.awt.Color(17, 19, 112));
        btJogar.setFont(new java.awt.Font("Abyssinica SIL", 0, 24)); // NOI18N
        btJogar.setForeground(new java.awt.Color(251, 249, 249));
        btJogar.setText("Jogar");
        btJogar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 163, 0), 3));
        btJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJogarActionPerformed(evt);
            }
        });

        btRecordes.setBackground(new java.awt.Color(194, 194, 7));
        btRecordes.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        btRecordes.setForeground(new java.awt.Color(240, 236, 236));
        btRecordes.setText("Recordes");
        btRecordes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 251, 251), 3));
        btRecordes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRecordesActionPerformed(evt);
            }
        });

        btRegras.setBackground(new java.awt.Color(39, 128, 4));
        btRegras.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        btRegras.setForeground(new java.awt.Color(244, 236, 236));
        btRegras.setText("Regras");
        btRegras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 251, 251), 3));
        btRegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegrasActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(181, 26, 6));
        btSair.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        btSair.setForeground(new java.awt.Color(248, 241, 241));
        btSair.setText("Sair");
        btSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 251, 251), 3));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 2, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 150, 0));
        jLabel1.setText(" Order Numbers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btJogar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRegras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRecordes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(55, 55, 55))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRegras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btRecordes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btRecordes, btRegras, btSair});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void MostrarTelaJogo(){
        if(jg==null){
            jg=new Jogo();
            jg.nome=nome.getText();
            jg.setVisible(true);
           dispose();
        }
    }
    
    private void btJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJogarActionPerformed
       
        MostrarTelaJogo();
       jg.tb.PreencherTabuleiro();
       jg.exibir();
        jg.Som=java.applet.Applet.newAudioClip(getClass().getResource("sound6.wav"));
        jg.Som.play();
        jg.iniciarContagem();
        
        
        
    }//GEN-LAST:event_btJogarActionPerformed

    private void btRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegrasActionPerformed
     TelaRegras tregras= new TelaRegras();
     tregras.setVisible(true);
    dispose();
    }//GEN-LAST:event_btRegrasActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btRecordesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecordesActionPerformed
        
        TelaRecordes tr= new TelaRecordes();
      tr.setVisible(true);
      dispose();
    }//GEN-LAST:event_btRecordesActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
       
       
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogar;
    private javax.swing.JButton btRecordes;
    private javax.swing.JButton btRegras;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome;
    // End of variables declaration//GEN-END:variables
}
