/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JogoOrderNumbers;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrique
 */
public class TelaRecordes extends javax.swing.JFrame {

  
   
    /**l
     * Creates new form TelaRecordes
     */
    public TelaRecordes() {
        initComponents();
       
        exibirRecordes();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jl1 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jl3 = new javax.swing.JLabel();
        jl4 = new javax.swing.JLabel();
        jl5 = new javax.swing.JLabel();
        jl11 = new javax.swing.JLabel();
        jl12 = new javax.swing.JLabel();
        jl21 = new javax.swing.JLabel();
        jl22 = new javax.swing.JLabel();
        jl31 = new javax.swing.JLabel();
        jl32 = new javax.swing.JLabel();
        jl41 = new javax.swing.JLabel();
        jl42 = new javax.swing.JLabel();
        jl51 = new javax.swing.JLabel();
        jl52 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 13, 1), 4));
        jPanel1.setForeground(new java.awt.Color(1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 3, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 109, 251));
        jLabel1.setText("Ranking!!! ");
        jLabel1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 121, 0));
        jLabel2.setText(" 5 Melhores");
        jLabel2.setFocusable(false);

        jl1.setBackground(new java.awt.Color(254, 254, 254));
        jl1.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl1.setForeground(java.awt.Color.white);
        jl1.setFocusable(false);

        jl2.setBackground(new java.awt.Color(254, 254, 254));
        jl2.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl2.setForeground(java.awt.Color.white);
        jl2.setFocusable(false);

        jl3.setBackground(new java.awt.Color(254, 254, 254));
        jl3.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl3.setForeground(java.awt.Color.white);
        jl3.setFocusable(false);

        jl4.setBackground(new java.awt.Color(254, 254, 254));
        jl4.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl4.setForeground(java.awt.Color.white);
        jl4.setFocusable(false);

        jl5.setBackground(new java.awt.Color(254, 254, 254));
        jl5.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl5.setForeground(java.awt.Color.white);
        jl5.setFocusable(false);

        jl11.setBackground(new java.awt.Color(254, 254, 254));
        jl11.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl11.setForeground(java.awt.Color.white);
        jl11.setFocusable(false);

        jl12.setBackground(new java.awt.Color(254, 254, 254));
        jl12.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl12.setForeground(java.awt.Color.white);
        jl12.setFocusable(false);

        jl21.setBackground(new java.awt.Color(254, 254, 254));
        jl21.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl21.setForeground(java.awt.Color.white);
        jl21.setFocusable(false);

        jl22.setBackground(new java.awt.Color(254, 254, 254));
        jl22.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl22.setForeground(java.awt.Color.white);
        jl22.setFocusable(false);

        jl31.setBackground(new java.awt.Color(254, 254, 254));
        jl31.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl31.setForeground(java.awt.Color.white);
        jl31.setFocusable(false);

        jl32.setBackground(new java.awt.Color(254, 254, 254));
        jl32.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl32.setForeground(java.awt.Color.white);
        jl32.setFocusable(false);

        jl41.setBackground(new java.awt.Color(254, 254, 254));
        jl41.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl41.setForeground(java.awt.Color.white);
        jl41.setFocusable(false);

        jl42.setBackground(new java.awt.Color(254, 254, 254));
        jl42.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl42.setForeground(java.awt.Color.white);
        jl42.setFocusable(false);

        jl51.setBackground(new java.awt.Color(254, 254, 254));
        jl51.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl51.setForeground(java.awt.Color.white);
        jl51.setFocusable(false);

        jl52.setBackground(new java.awt.Color(254, 254, 254));
        jl52.setFont(new java.awt.Font("Abyssinica SIL", 2, 14)); // NOI18N
        jl52.setForeground(java.awt.Color.white);
        jl52.setFocusable(false);

        btVoltar.setBackground(new java.awt.Color(20, 105, 10));
        btVoltar.setFont(new java.awt.Font("Abyssinica SIL", 3, 18)); // NOI18N
        btVoltar.setForeground(new java.awt.Color(250, 250, 254));
        btVoltar.setText("Voltar");
        btVoltar.setFocusable(false);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(197, 31, 12));
        btSair.setFont(new java.awt.Font("Abyssinica SIL", 3, 18)); // NOI18N
        btSair.setForeground(new java.awt.Color(254, 254, 254));
        btSair.setText("Sair");
        btSair.setFocusable(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jl2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(jl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jl52, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(jl42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jl22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl31, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(jl3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jl32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl41, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl42, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jl5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jl51, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jl52, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jl1, jl2, jl3, jl4, jl5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jl11, jl21, jl31, jl41, jl51});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btSair, btVoltar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        TelaMenu ti= new TelaMenu();
        ti.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRecordes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRecordes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRecordes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRecordes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRecordes().setVisible(true);
               
            }
        });
       
         
    }
    public void exibirRecordes(){
        ConectarMysql conectar=new ConectarMysql();
        conectar.conectar();
        String sql="Select * from Jogador order by jogadas";
         
         int cont=1;
       try {
          ResultSet rs= conectar.conectar().prepareStatement(sql).executeQuery();
          rs.first();
          
  do{
      
      if(cont==1){
          cont++;
          jl1.setText(rs.getString("nome"));
          jl11.setText(rs.getString("jogadas"));
          jl12.setText(rs.getString("tempo"));
      }else if(cont==2){
          cont++;
          jl2.setText(rs.getString("nome"));
          jl21.setText(rs.getString("jogadas"));
          jl22.setText(rs.getString("tempo"));
      }else if(cont==3){
          cont++;
          jl3.setText(rs.getString("nome"));
          jl31.setText(rs.getString("jogadas"));
          jl32.setText(rs.getString("tempo"));   
      }else if(cont==4){
          cont++;
          jl4.setText(rs.getString("nome"));
          jl41.setText(rs.getString("jogadas"));
          jl42.setText(rs.getString("tempo"));   
      } else if(cont==5){
          jl5.setText(rs.getString("nome"));
          jl51.setText(rs.getString("jogadas"));
          jl52.setText(rs.getString("tempo"));  
      }else;
      
  }while(rs.next());
         
       } catch (SQLException ex) {
          System.out.println("Não deu certo");
       }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl11;
    private javax.swing.JLabel jl12;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl21;
    private javax.swing.JLabel jl22;
    private javax.swing.JLabel jl3;
    private javax.swing.JLabel jl31;
    private javax.swing.JLabel jl32;
    private javax.swing.JLabel jl4;
    private javax.swing.JLabel jl41;
    private javax.swing.JLabel jl42;
    private javax.swing.JLabel jl5;
    private javax.swing.JLabel jl51;
    private javax.swing.JLabel jl52;
    // End of variables declaration//GEN-END:variables
}
